language: python
python:
  - "3.6"
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
before_install:
  - touch /tmp/hass.cer
  - touch /tmp/hass.key
  - mv travis_secrets.yaml secrets.yaml
