# 00-core.yaml
# This file performs the basic configuration of Home Assistant's core
# components.

http:
    api_password: !secret HTTP_PASS
    ssl_certificate: !secret SSL_CERT_PATH
    ssl_key: !secret SSL_KEY_PATH
    server_port: 443
    base_url: !secret BASE_URL

updater:
history:
frontend:
conversation:
logbook:
config:

tts:
    platform: google

logger:
    default: warning
    logs:
        custom_components.lighting_schedule: debug

homeassistant:
  name: Home
  latitude: !secret HOME_LAT
  longitude: !secret HOME_LON
  elevation: !secret HOME_ELEVATION
  unit_system: imperial
  time_zone: America/New_York
  customize:
        switch.away:
            hidden: true
        binary_sensor.garage_door_sensor:
            hidden: true
        switch.lrfan:
            friendly_name: Fan
        light.lraccent_lights:
            friendly_name: Accent Lights
        light.lrlights:
            friendly_name: Lights
        light.ktlights:
            friendly_name: Lights
        light.ktbar_lights:
            friendly_name: Bar Lights
        light.ktsink_light:
            friendly_name: Sink Light
        light.kttable_light:
            friendly_name: Table Light
        light.drlights:
            friendly_name: Lights
        light.drlamp:
            friendly_name: Lamp
        light.drtree:
            friendly_name: Tree
        light.folight:
            friendly_name: Lights
        light.byporch:
            friendly_name: Back Porch
        light.byflood_1:
            friendly_name: Back Flood 1
        light.byflood_2:
            friendly_name: Back Flood 2
        light.fyporch_light:
            friendly_name: Front Porch
        light.fycarriage_lights:
            friendly_name: Front Carriage Lights
        light.msseasonal_lights:
            friendly_name: Seasonal Lights
        light.mblights:
            friendly_name: Lights
        switch.ebtv:
            friendly_name: TV
        light.ebstars:
            friendly_name: Stars
        light.livingcolors_1:
            friendly_name: Color Light
        switch.garage_door_control:
            hidden: true
        sensor.dark_sky_temperature:
            friendly_name: Outside Temp
        sensor.dark_sky_summary:
            friendly_name: Summary
        sensor.dark_sky_precip_intensity:
            friendly_name: Precip Intensity
            icon: mdi:weather-rainy
        sensor.dark_sky_precip_probability:
            friendly_name: Precip Probability
            icon: mdi:weather-rainy
        sensor.dark_sky_humidity:
            friendly_name: Humidity
            icon: mdi:water-percent
        sensor.dark_sky_wind_speed:
            friendly_name: Wind Speed
            icon: mdi:weather-windy
        switch.living_room_tv:
            hidden: true
        media_player.living_room:
            hidden: true
        switch.living_room_mute:
            hidden: true
        device_tracker.pcsupsbf_ryan:
            hidden: true
        switch.dim:
            hidden: true
        switch.dim_2:
            hidden: true
        switch.bright:
            hidden: true
        switch.bright_2:
            hidden: true
        switch.movie:
            hidden: true
        switch.movie_2:
            hidden: true
        switch.night:
            hidden: true
        script.bright_on:
            hidden: true
        script.dim_on:
            hidden: true
        script.movie_on:
            hidden: true
        script.night_on:
            hidden: true
        sensor.average_temperature_tomorrow:
            hidden: true
        sensor.dew_point:
            hidden: true
        sensor.elevation:
            hidden: true
        sensor.evapotranspiration:
            hidden: true
        sensor.feels_like:
            hidden: true
        sensor.forecast_average_temperature:
            hidden: true
        sensor.forecast_high_temperature:
            hidden: true
        sensor.forecast_humidity:
            hidden: true
        sensor.forecast_low_temperature:
            hidden: true
        sensor.forecast_rain:
            hidden: true
        sensor.forecast_snow:
            hidden: true
        sensor.gust_speed:
            hidden: true
        sensor.gust_speed_tomorrow:
            hidden: true
        sensor.high_temperature_tomorrow:
            hidden: true
        sensor.humidity_tomorrow:
            hidden: true
        sensor.irrigation_requirement:
            hidden: true
        sensor.low_temperature_tomorrow:
            hidden: true
        sensor.pressure:
            hidden: true
        sensor.rain_tomorrow:
            hidden: true
        sensor.snow_tomorrow:
            hidden: true
        sensor.temperature_average:
            hidden: true
        sensor.temperature_high:
            hidden: true
        sensor.temperature_low:
            hidden: true
        sensor.water_deficit_yesterday:
            hidden: true
        sensor.wind_speed_tomorrow:
            hidden: true
        sensor.humidity:
            hidden: true
        sensor.light:
            hidden: False
        sensor.temperature:
            hidden: True
        sensor.total_rain_today:
            hidden: True
        sensor.wind_direction:
            hidden: True
        sensor.wind_speed:
            hidden: True
        script.bright_outside:
            hidden: True
        script.dark_outside:
            hidden: True
        input_boolean.dark_outside:
            hidden: True

