# 91-daily_schedule.yaml
# This file contains automations controlling daily actions around the house.

input_boolean:
    dark_outside:
        name: 'It is dark outside'
        initial: on


automation:
    # when light is less than 15%, it is dark outside
  - alias: "It is dark outside"
    hide_entity: True
    trigger:
        platform: numeric_state
        entity_id: sensor.light
        below: 12
    action:
        service: homeassistant.turn_on
        entity_id: script.dark_outside

    # turn on outside lights when it is dark
  - alias: "It is bright outside"
    hide_entity: True
    trigger:
        platform: numeric_state
        entity_id: sensor.light
        above: 15
    action:
        service: homeassistant.turn_on
        entity_id: script.bright_outside
